### ISSUE TITLE
Is it possible to use scmpy to load a saved Set Covering Machine?

### ISSUE THREAD

**Issue by augustkx** [younik/SetCoveringMachine#3]
For example, in forms of 
>rule-1 presence, importance: 1.00
AAAAAAAATAAAATGACACACAAGACCAGCT
 

>rule-1-equiv-1,presence
AAAAATTCACCACATCCCTCACAACCACCTT

>rule-1-equiv-2,presence
AAAACCAATCAGAAAGATCGTCGACGACAGG

Thanks in advance!

**Comment by younik** [comment]
Hello @augustkx, thanks for your suggestion!
I think implementing a load/save mechanism should be easy.

Though I didn't get completely how you are suggesting to encode it. Can you explain it more? Do you want to contribute to this?

**Comment by augustkx** [comment]
Hi younik,
Thanks for your quick reply very much. You are right, it is easy(everyone told me it is easy....so I rethink on it...), I misunderstood the SCM model last week. No concerns from my side now.

**Comment by younik** [comment]
Yes, you can simply use pickle or we can make personalized load/save methods.
